services:
  db:
    image: postgres:17
    container_name: gba-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - gba-db-data:/var/lib/postgresql/data

  gba-api:
    build: ./gba-api
    container_name: gba-api
    env_file:
      - gba-api/.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./gba-api/uploads/users:/app/uploads/users

  gba-front:
    build: ./gba-front
    container_name: gba-front
    env_file:
      - gba-front/.env
    ports:
      - "3001:80"

  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - gba-api
      - gba-front

volumes:
  gba-db-data: