services:
  gba-api:
    build: ./gba-api
    container_name: gba-api
    ports:
      - "5000:5000"
    volumes:
      - ./gba-api/uploads/roms:/app/uploads/roms

  gba-front:
    build: ./gba-front
    container_name: gba-front
    ports:
      - "3001:80"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - gba-api
      - gba-front