services:
  db:
    image: postgres:17
    container_name: gba-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - gba-db-data:/var/lib/postgresql/data

  gba-api:
    image: ${API_IMAGE}
    container_name: gba-api
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - user-data:/app/uploads/users

  gba-front:
    image: ${FRONT_IMAGE}
    container_name: gba-front
    ports:
      - "3001:80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gba-api
      - gba-front

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  gba-db-data:
  user-data:
