name: GBA to AWS

on:
  push:
    branches: [ main ]
    paths:
      - gba-api/**
      - gba-front/**
      - docker-compose.yml
  pull_request: 
    branches: [ main ]
    paths: 
      - gba-api/**
      - gba-front/**
      - docker-compose.yml

env:
  COMPOSE: docker-compose.yml

jobs:
  build:
    name: Building images and pushing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./gba-api
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/gba-api

      - name: Build and push Front image
        uses: docker/build-push-action@v5
        with:
          context: ./gba-front
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/gba-front
      
  aws:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.AWS_HOSTNAME}}
          username: ${{secrets.AWS_USERNAME}}
          port: 22
          key: ${{secrets.AWS_PRIVATE_KEY}}
          source: ${{env.COMPOSE}}
          target: /home/admin
        
      - name: Deploy docker services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AWS_HOSTNAME}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_PRIVATE_KEY}}
          port: 22
          script: |
            sleep 30
            docker compose down
            sleep 5
            docker rmi ${{secrets.DOCKERHUB.USERNAME}}/gba-api ${{secrets.DOCKERHUB.USERNAME}}/gba-front
            sleep 5
            docker compose up -d nginx